language: node_js
node_js:
  - '12'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: sitmun    

cache:
  directories:
    - ./node_modules

before_install:
  - npm set //npm.pkg.github.com/:_authToken $GITHUB_API_KEY

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
  - npm run sonar